- name: catalogue deployment
  hosts:  catalogue 
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command:  dnf mondule enable nodejs:20
  - name: dnf install 
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: create user
    ansible.builtin.user:
      name: roboshop
      system: yes
      shell: /sbin/nologin
      home: /app
      comment: "roboshop system user"
  - name: create directory
    ansible.bultin.file:
      path: /app
      state: directory
  - name: download the application
    ansible.builtin.geturl:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip  
      dest: /tmp/catalogue.zip
  - name: ansible unzip file
    ansible.builtin.unarchive:
      src:  /tmp/catalogue.zip
      dest: /app

