[mongodb]
mongodb-dev.ananthsolutions.online

[catalogue]
catalogue-dev.ananthsolutions.online

[redis]
redis-dev.ananthsolutions.online

[user]
user-dev.ananthsolutions.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.ananthsolutions.online