[mongodb]
mongodb-dev.ananthsolutions.online

[catalogue]
catalogue-dev.ananthsolutions.online

[redis]
redis-dev.ananthsolutions.online

[user]
user-dev.ananthsolutions.online

[cart]
cart-dev.ananthsolutions.online

[mysql]
mysql-dev.ananthsolutions.online

[shipping]
shipping-dev.ananthsolutions.online

[rabbitmq]
rabbitmq-dev.ananthsolutions.online

[payment]
payment-dev.ananthsolutions.online

[frontend]
frontend-dev.ananthsolutions.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.ananthsolutions.online
REDIS_HOST=redis-dev.ananthsolutions.online
CATALOGUE_HOST=catalogue-dev.ananthsolutions.online
MYSQL_HOST=mysql-dev.ananthsolutions.online
CART_HOST=cart-dev.ananthsolutions.online
RABBIT_HOST=rabbitmq-dev.ananthsolutions.online
USER_HOST=user-dev.ananthsolutions.online
SHIPPING_HOST=shipping-dev.ananthsolutions.online
PAYMENT_HOST=frontend-dev.daws88s.online