- name: mondo db confugration
  hosts: mongodb
  become: yes
  tasks:
  - name: moving files to server
    ansible.builtin.copy:
      src: /home/ec2-user/roboshop-ansible/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  - name: updating the host details
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
  - name: enable the mongodb    
    ansible.builtin.systemd:
      name: mongod
      enabled: yes
      state: started

